version: '3.8'

services:
  backend:
    build: backend
    hostname: backend-host 
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - shri-network

  frontend:
    build: frontend
    hostname: frontend-host 
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend-host:8000/api
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on:
      - backend
    networks:
      - shri-network


networks:
  shri-network: {}


